- .github/workflows/Deploy-WASM-Storage.yml
- .github/workflows/Deploy.yml
It's easier to onboard new developers using a CI secret instead of manually specifying allowed users.
Use a workflow dispatch input and secret variable to allow running the rest of the workflow.
I also set CI_PASSWORD already for this repository.
Tested on a fork of this repository
Related to https://github.com/sedaprotocol/seda-chain/issues/12
> chore: manual deploy CI secret

- packages/seda-chain-contracts/src/data_request_result.rs
- packages/seda-chain-contracts/src/error.rs
Replace some assertions/panics with errors with error strings.
- Added new errors to error enum
- Replace assertions/panics with error
- Confirm tests still run
I noticed some errors aren't being tested, so I created this PR as to keep this one minimal: https://github.com/sedaprotocol/seda-chain-contracts/issues/58
> refactor: use errors instead of assertions/panics

- packages/data-requests/src/data_request.rs
- packages/data-requests/src/utils.rs
- packages/integration-tests/src/data_request.rs
- packages/integration-tests/src/data_result.rs
The DR hashing function incorrectly includes `payback_address` and `seda_payload`, which are not known by external chains at time of DR creation.
- Removed `payback_address` and `seda_payload` from DR hashing function
- Refactored memo hash to remove `value`, keeping only `chain_id` and `nonce`. This is only to reflect how memo is calculated in the EVM contracts, i.e. the CosmWasm contracts don't care about how memo is calculated.
- Removed deprecated util functions `hash_update()` and `pad_to_32_bytes()` since the hashing function no longer requires them
- Created a new test `test_hash_data_request()` to isolate the DR hashing function and to mirror an identical test on the EVM repo, see: https://github.com/sedaprotocol/seda-evm-contracts/blob/20fffd45abcdcd16e27c4f8ef0a4c343e0dbc371/test …
> fix: update hashing function to latest spec

- packages/data-requests/src/data_request.rs
- packages/data-requests/src/msg.rs
Query responses return a Response with the data property. To make it easier to get the data request ID after posting a data request, this PR also returns it in the execute message `PostDataRequest`.
- return `dr_id` in response.data in `post_data_requests`
I could not identify any other functions where return data is necessary. 
n/a, tests still passing
Closes #51
> refactor: return dr_id in response.data in `PostDataRequest` message

- .github/workflows/Basic.yml
- .github/workflows/Deploy.yml
- .github/workflows/Release.yml
Better maintainability.
Bumped rust version in GitHub workflows to 1.72.1, mainly to fix failing test in this PR: https://github.com/sedaprotocol/seda-chain-contracts/pull/76 since it uses the (previously) unstable library feature `is_some_with`.
Tested https://github.com/sedaprotocol/seda-chain-contracts/pull/76 with bumped rust version locally.
N/A
> chore: bump github actions rust toolchain

- Cargo.lock
- contract/Cargo.toml
- contract/src/msgs/data_requests/sudo/remove_requests.rs
- contract/src/msgs/staking/execute/staking_events.rs
- contract/src/types.rs
More events for the indexer.
Emits all stakers effected, i.e. who got rewards, after we are done processing all removals and distributions.
All tests should still pass.
N/A
> chore: emit staker events post dr removal

- Cargo.lock
- contract/Cargo.toml
- contract/src/msgs/data_requests/execute/mod.rs
- contract/src/msgs/data_requests/tests.rs
- contract/src/msgs/owner/execute/remove_from_allowlist.rs
- contract/src/msgs/owner/tests.rs
- contract/src/msgs/staking/execute/mod.rs
- contract/src/msgs/staking/tests.rs
So that pausing prevents execution messages in case there are contract problems.
And that removing someone from the allowlist no longer makes them an executor.
In the `mod.rs` file of both the `data_request` and `staking` execute modules now check if the contract is paused. If it is we don't allow the execute messages to go through, with the exception of their respective owner messages.
Also did the allowlist changes in this PR.
So removing someone from the allowlist now moves their staked tokens to the pending withdraw.
Adds tests to check that.
I did move the one test that was in owner tests to data request test as it makes more sense to be there.
Added tests for the allowlist stuff as well.
N/A
> fix: pause and allowlist discrepancies

- Cargo.lock
- contract/Cargo.toml
- contract/src/contract.rs
- contract/src/error.rs
- contract/src/msgs/staking/execute/set_staking_config.rs
- contract/src/msgs/staking/tests.rs
To not allow stake to be zero since it breaks behavior.
Disallow both stake fields from being zero.
Two new tests.
N/A
> fix: do not allow stake amounts to be zero

- Cargo.lock
- contract/Cargo.toml
- contract/src/contract.rs
- contract/src/msgs/data_requests/query.rs
- contract/src/msgs/data_requests/tests.rs
Since we now always continue the flow and that way tally can always resolve
> chore: no longer return empty drs when paused

- README.md
To have a short description on what the repo is.
Adds a blurb to the top level of the readme.
N/A
N/A
> docs: Short blurb

- Cargo.lock
- Cargo.toml
- contract/Cargo.toml
- contract/src/msgs/data_requests/sudo/remove_requests.rs
- contract/src/msgs/data_requests/tests.rs
- contract/src/msgs/staking/tests.rs
- xtask/src/main.rs
So that the call does not error and cause data request processing to halt.
- Updates common to change the field in data proxy reward `to: Binary` to `payout_address: String`.
- Updates dep versions, only big change is cosmwasm see rationale on why in the [common pr](https://github.com/sedaprotocol/seda-common-rs/pull/41).
- If an invalid address, identity, or non existent identity comes up, those funds are burned.
Updated tests and added the new cases to the remove data request test.
Waiting on https://github.com/sedaprotocol/seda-common-rs/pull/41 to merge so we can update it here.
> fix: burn funds for invalid address/identity

- contract/src/msgs/data_requests/tests.rs
- contract/src/test_utils.rs
To add some tests for edge cases.
Adds tests for:
- staker unstaking before being rewarded
- data request running out of funds
- a user can reveal after unstaking
The only things I noticed that might be worth double checking are:
- A staker can commit and reveal on their own data requests. The math for available executors also accounts for this. But this seems fine to me? There doesn't seem like there would be any conflict of interests for this.
- In remove data requests we don't check that the data request being removed is in the tally state. We simply trust the DRs the chain passes.
Tests pass.
N/A
> test: unstaking edge cases

- Cargo.lock
- Cargo.toml
- contract/Cargo.toml
- contract/src/msgs/staking/query.rs
- contract/src/msgs/staking/test_helpers.rs
- contract/src/msgs/staking/tests.rs
To be able to query executors in a paginated fashion.
Imports the new query and result from common.
Uses the `EnumerableSet` to grab the users, then maps them to their information.
Added new tests to check behavior.
~~Blocked by https://github.com/sedaprotocol/seda-common-rs/pull/42 being merged and updating the toml.~~
Closes #266.
> feat: paginated executors query

- Cargo.lock
- common/src/msgs/staking/execute/withdraw.rs
- common/src/msgs/staking/execute_tests.rs
- contract/src/error.rs
- contract/src/msgs/staking/execute/withdraw.rs
- contract/src/msgs/staking/test_helpers.rs
- contract/src/msgs/staking/tests.rs
So you cannot frontrun withdrawing.
- Adds the withdraw address to the withdraw payload.
- modifies the hashes accordingly
Two new tests added that pass.
N/A
> Fix: withdrawal frontrun

- common/src/msgs/data_requests/execute/commit_result.rs
- common/src/msgs/data_requests/execute/reveal_result.rs
- common/src/msgs/data_requests/execute_tests.rs
- common/src/msgs/data_requests/types.rs
- common/src/msgs/data_requests/types_tests.rs
- contract/src/msgs/data_requests/execute/reveal_result.rs
- contract/src/msgs/data_requests/test_helpers.rs
- contract/src/msgs/data_requests/tests/commit_dr.rs
- contract/src/msgs/data_requests/tests/pause_behavior.rs
- contract/src/msgs/data_requests/tests/query_dr_status.rs
- contract/src/msgs/data_requests/tests/remove_dr.rs
- contract/src/msgs/data_requests/tests/reveal_dr.rs
- contract/src/msgs/data_requests/tests/timeout_actions.rs
- contract/src/msgs/staking/tests.rs
- contract/src/test_utils.rs
- xtask/src/main.rs
Bring implementation up to date with the spec found here: https://www.notion.so/sedaprotocol/20240227-Implementation-of-Commitment-Scheme-1a7a68d575ca80c3966dc03c3488ce61
This prevents front-running and freeloading as the commitment now includes private material from the executor identity that created the reveal message.
- Commitment is now the hash of the of the reveal message rather than just the reveal body.
- Reveal Body removes the salt, and adds the dr height.
Tests updated and new ones added.
N/A
> Fix: commit reveal

- common/src/msgs/data_requests/query.rs
- common/src/msgs/data_requests/query_tests.rs
- common/src/msgs/data_requests/types.rs
- contract/src/msgs/data_requests/execute/commit_result.rs
- contract/src/msgs/data_requests/execute/post_request.rs
- contract/src/msgs/data_requests/execute/reveal_result.rs
- contract/src/msgs/data_requests/query.rs
- contract/src/msgs/data_requests/state/data_requests_map.rs
- contract/src/msgs/data_requests/state/data_requests_map_tests.rs
- contract/src/msgs/data_requests/state/mod.rs
- contract/src/msgs/data_requests/sudo/remove_requests.rs
- contract/src/msgs/data_requests/test_helpers.rs
- contract/src/msgs/data_requests/tests/commit_dr.rs
- contract/src/msgs/data_requests/tests/pause_behavior.rs
- contract/src/msgs/data_requests/tests/post_dr.rs
- contract/src/msgs/data_requests/tests/query_dr_status.rs
- contract/src/msgs/data_requests/tests/remove_dr.rs
- contract/src/msgs/data_requests/tests/reveal_dr.rs
- contract/src/msgs/data_requests/tests/timeout_actions.rs
- contract/src/msgs/mod.rs
- contract/src/msgs/sorted_set.rs
- xtask/src/main.rs
An alternate way from #278 to handle sorting data requests by price.
This is an alternate approach where we no longer have to worry about "precise" pagination.
> [!NOTE]
> Pagination is not precise in the current `fix-review` branch due to swap remove.
> The only branch to have precise pagination is #278 and it comes at a cost, see that PR for details.
- Creates a data structure that has the `gas_price`,  `height`, `dr_id`.
- This is used as an index within a Map to keep insertion and removal `O(1)`.
- You can get a full index key from a `dr_id`.
- The pagination query, now returns and takes an optional (last index key).
- If provided to the query it starts pagination from here.
> [!NOTE]
> This approach does lead to a imprecise "pagination", but that's the same as the current …
> Feat: price sorted set

- contract/src/consts.rs
- contract/src/contract.rs
- contract/src/msgs/data_requests/tests/reveal_dr.rs
- contract/src/msgs/data_requests/tests/timeout_actions.rs
- contract/src/msgs/staking/query.rs
- contract/src/msgs/staking/state/is_eligible_for_dr.rs
- contract/src/test_utils.rs
If some executors go offline, the existing query logic could fail to resolve data requests due to insufficient commits.
This posed a risk where a subset of available executors could not fulfill the request alone, resulting in an availability risk.
1. The replication factor now increases incrementally with each block that passes after a data request is posted. This enables other allow-listed executors to step in if the original ones are unavailable.
2. This PR also sets default staking configuration values that align with the parameters planned for the mainnet upgrade, ensuring a smoother transition and consistent validator experience.
Added tests for replication factor growth.
N/A
> feat(staking): improve query is eligible

- contract/src/consts.rs
- contract/src/contract.rs
- contract/src/legacy.rs
- contract/src/lib.rs
- contract/src/msgs/data_requests/tests/commit_dr.rs
- contract/src/msgs/data_requests/tests/timeout_actions.rs
Since all deployed contracts are on the latest version we'll never need
the migration logic again.
With the defaults at the values we decided on we won't need to immediately change the settings after deploying on mainnet.
N.A.
Updated unit tests.
N.A.
> Update defaults and remove legacy

- Cargo.lock
- common/Cargo.toml
- common/src/msgs/data_requests/query.rs
- common/src/msgs/data_requests/types.rs
- common/src/msgs/data_requests/types_tests.rs
- contract/Cargo.toml
- contract/src/msgs/data_requests/execute/commit_result.rs
- contract/src/msgs/data_requests/execute/post_request.rs
- contract/src/msgs/data_requests/execute/reveal_result.rs
- contract/src/msgs/data_requests/query.rs
- contract/src/msgs/data_requests/state/data_requests_map.rs
- contract/src/msgs/data_requests/state/data_requests_map_tests.rs
- contract/src/msgs/data_requests/state/mod.rs
- contract/src/msgs/data_requests/sudo/remove_requests.rs
- contract/src/msgs/data_requests/test_helpers.rs
- contract/src/msgs/data_requests/tests/commit_dr.rs
- contract/src/msgs/data_requests/tests/post_dr.rs
- contract/src/msgs/data_requests/tests/query_dr_status.rs
- contract/src/msgs/data_requests/tests/remove_dr.rs
- contract/src/msgs/data_requests/tests/reveal_dr.rs
- contract/src/msgs/data_requests/tests/timeout_actions.rs
- contract/src/msgs/sorted_set.rs
- contract/src/msgs/staking/state/is_eligible_for_dr.rs
- xtask/src/main.rs
So that revealers don't run into gas issues.
- Adds a new field reveals to the `DataRequestsMap` which contains the reveals for all DRs.
- They are keyed by `dr_id:identity`.
- `DataRequest` struct has been changed:
- `DataRequestBase` which has all the fields but the reveals.
- `DataRequestContract` where the reveals field is a `HashSet` of identities that have revealed and it composes the base.
- `DataRequestResponse` where the reveals field is the original `HashMap` and it composes the base, and preserves the same JSON serialization and de-serialization.
- The old methods have been split among these types, but functionally remain the same.
- New methods to manage create, read, and delete operations for said reveals.
- All old tests still pass with the only changed logic being accessing …
> refactor: separate reveal storage

- Cargo.lock
- common/Cargo.toml
- common/src/msgs/data_requests/types.rs
- common/src/msgs/data_requests/types_tests.rs
- contract/Cargo.toml
- contract/src/consts.rs
- contract/src/contract.rs
- contract/src/error.rs
- contract/src/msgs/data_requests/execute/post_request.rs
- contract/src/msgs/data_requests/execute/reveal_result.rs
- contract/src/msgs/data_requests/state/data_requests_map.rs
- contract/src/msgs/data_requests/state/data_requests_map_tests.rs
- contract/src/msgs/data_requests/tests/commit_dr.rs
- contract/src/msgs/data_requests/tests/pause_behavior.rs
- contract/src/msgs/data_requests/tests/post_dr.rs
- contract/src/msgs/data_requests/tests/reveal_dr.rs
- contract/src/msgs/data_requests/tests/timeout_actions.rs
- contract/src/msgs/staking/state/is_eligible_for_dr.rs
To limit the amount of bytes a posted dr can take up in storage.
Important Changes:
- Adds the new dr config fields to limit input, consensus filter, and memo sizes. And defaults for them.
- Checks that when posting a dr those fields constrain to those limits.
- Also checks when posting a dr the program ids are the proper size.
Minor Changes:
- Converts all dr config fields to NonZero types.
- Shrinks the existing dr config field types. Might as well, as we are unlikely to go past these limits and shrinks storage.
Added new tests to test the limits.
[chain]: https://github.com/sedaprotocol/seda-chain
[explorer]: https://github.com/sedaprotocol/seda-explorer
[overlay-rs]: https://github.com/sedaprotocol/overlay-rs
[overlay-ts]: https://github.com/sedaprotocol/seda-overlay-ts
[sdk]: …
> Feat: dr field limits

- Cargo.lock
- contract/Cargo.toml
- contract/src/msgs/staking/state/is_eligible_for_dr.rs
Given that the backup delay is intended to give executors a chance to execute the data request and commit their result, it makes sense that executors that become avaible due to the backup replication factor also get the chance to execute the DR. When executors became available at every block we saw that this lead to a lot of executor work being wasted, especially under higher loads, contributing to even more congestion.
Simply dividing the passed blocks by the delay (while accounting for the 'extra block' needed at the start) gives us the amount of additional executors.
Updated the tests.
N.A.
> Wait the backup delay for every additional executor

- Cargo.lock
- common/Cargo.toml
- common/src/msgs/data_requests/query.rs
- common/src/msgs/data_requests/query_tests.rs
- common/src/msgs/data_requests/types.rs
- contract/Cargo.toml
- contract/src/error.rs
- contract/src/msgs/data_requests/query.rs
- contract/src/msgs/data_requests/tests/query_dr_status.rs
- contract/src/msgs/sorted_set.rs
Makes the last seen index human readable.
- The index before was in reverse mode to sort by height correctly but it caused confusion when the height in the last seen index was very high.
- The dr_id is now a string for convenience rather than the byte array.
- The height in the last seen index is now a string since JS doesn't like those.
All tests still pass.
[chain]: https://github.com/sedaprotocol/seda-chain
[explorer]: https://github.com/sedaprotocol/seda-explorer
[overlay-rs]: https://github.com/sedaprotocol/overlay-rs
[overlay-ts]: https://github.com/sedaprotocol/seda-overlay-ts
[sdk]: https://github.com/sedaprotocol/seda-sdk
Think about the changes(msgs, events, limits, etc.) made in this PR and see if you need to make an issue/pr on the following repos.
N/A
> refactor: make last seen index human readable

- common/src/msgs/staking/query_tests.rs
- common/src/msgs/staking/types.rs
To have correct deserialization for the new query outside of the contract.
- Adds the attribute so the JSON tries to deserialize from snake case
I don't think this justifies creating a new version per se, the rust overlay can just point to this branch/main once it's merged.
Adds tests for both the query and the response.
[chain]: https://github.com/sedaprotocol/seda-chain
[explorer]: https://github.com/sedaprotocol/seda-explorer
[overlay-rs]: https://github.com/sedaprotocol/overlay-rs
[overlay-ts]: https://github.com/sedaprotocol/seda-overlay-ts
[sdk]: https://github.com/sedaprotocol/seda-sdk
Think about the changes(msgs, events, limits, etc.) made in this PR and see if you need to make an issue/pr on the following repos.
N/A
> Fix(common): Get Elig Exec Json Issues

- Cargo.lock
- common/Cargo.toml
- contract/Cargo.toml
- contract/src/error.rs
- contract/src/msgs/data_requests/execute/commit_result.rs
- contract/src/msgs/data_requests/tests/commit_dr.rs
- contract/src/msgs/staking/execute/stake.rs
Provides a clearer error message by distinguishing between insufficient stake vs insufficient attached funds.
> Separate errors for insufficient funds and insufficient stake

- Cargo.lock
- common/Cargo.toml
- contract/Cargo.toml
- contract/src/consts.rs
Update this to match the values we've been using on testnet.
Update backup_delay to be 5 blocks.
All tests still pass
[chain]: https://github.com/sedaprotocol/seda-chain
[explorer]: https://github.com/sedaprotocol/seda-explorer
[overlay-rs]: https://github.com/sedaprotocol/overlay-rs
[overlay-ts]: https://github.com/sedaprotocol/seda-overlay-ts
[sdk]: https://github.com/sedaprotocol/seda-sdk
Think about the changes(msgs, events, limits, etc.) made in this PR and see if you need to make an issue/pr on the following repos.
N/A
> fix: initial backup delay value was wrong
